/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/native/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Native Start */
        post: operations["native_start_api_v1_auth_native_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/native/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Native Exchange */
        post: operations["native_exchange_api_v1_auth_native_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/native/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Native Refresh */
        post: operations["native_refresh_api_v1_auth_native_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/native/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Native Revoke */
        post: operations["native_revoke_api_v1_auth_native_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/native/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Native Session */
        get: operations["native_session_api_v1_auth_native_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_v1_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/artifacts/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign Activity Artifact */
        post: operations["presign_activity_artifact_api_v1_activities__activity_id__artifacts_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/artifacts/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Activity Artifact */
        post: operations["confirm_activity_artifact_api_v1_activities__activity_id__artifacts_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/source-visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Activity Source Visibility */
        post: operations["set_activity_source_visibility_api_v1_activities__activity_id__source_visibility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/commit-output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Activity Output */
        post: operations["commit_activity_output_api_v1_activities__activity_id__commit_output_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/self-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Activity Self Review */
        post: operations["submit_activity_self_review_api_v1_activities__activity_id__self_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Activity */
        post: operations["start_activity_api_v1_activities__activity_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Activity */
        post: operations["pause_activity_api_v1_activities__activity_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Activity */
        post: operations["resume_activity_api_v1_activities__activity_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat Activity */
        post: operations["heartbeat_activity_api_v1_activities__activity_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/classify-incomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify Activity Incomplete */
        post: operations["classify_activity_incomplete_api_v1_activities__activity_id__classify_incomplete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill */
        get: operations["get_skill_api_v1_skills__skill_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill_slug}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skill Evidence */
        get: operations["list_skill_evidence_api_v1_skills__skill_slug__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activity Evidence */
        get: operations["list_activity_evidence_api_v1_activities__activity_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio-judgment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio History */
        get: operations["get_portfolio_history_api_v1_portfolio_judgment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notification Read */
        post: operations["mark_notification_read_api_v1_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Status Events */
        get: operations["stream_status_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmap-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Roadmap Import */
        post: operations["create_roadmap_import_api_v1_roadmap_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmap-imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roadmap Import */
        get: operations["get_roadmap_import_api_v1_roadmap_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmap-imports/{import_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Roadmap Import */
        post: operations["approve_roadmap_import_api_v1_roadmap_imports__import_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmap-imports/{version_id}/mirror/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Roadmap Mirror */
        post: operations["retry_roadmap_mirror_api_v1_roadmap_imports__version_id__mirror_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmap-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roadmap Versions */
        get: operations["list_roadmap_versions_api_v1_roadmap_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmap-versions/{version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Roadmap Version */
        post: operations["activate_roadmap_version_api_v1_roadmap_versions__version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_api_v1_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/today/{local_date}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Today */
        post: operations["close_today_api_v1_today__local_date__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityDetailResponse */
        ActivityDetailResponse: {
            /** Id */
            id: number;
            /** Study Day Id */
            study_day_id: number;
            state: components["schemas"]["ActivityState"];
            /** Optimistic Version */
            optimistic_version: number;
            classification: components["schemas"]["IncompleteClassification"];
            /** Stronger Evidence Id */
            stronger_evidence_id: number | null;
            /** Activity Focused Seconds */
            activity_focused_seconds: number;
            /** Day Focused Minutes */
            day_focused_minutes: number;
            /** Hard Stop Recommended */
            hard_stop_recommended: boolean;
            open_timer: components["schemas"]["TimerResponse"] | null;
            /**
             * Source Hidden
             * @default false
             */
            source_hidden: boolean;
            task_contract: components["schemas"]["ActivityTaskContract"];
            committed_output?: components["schemas"]["CommittedOutputSummary"] | null;
            self_review?: components["schemas"]["SelfReviewSummary"] | null;
        };
        /** ActivityProcedureStep */
        ActivityProcedureStep: {
            /** Phase */
            phase: string;
            /** Minutes */
            minutes?: number | null;
            /** Requirement */
            requirement: string;
        };
        /** ActivityResponse */
        ActivityResponse: {
            /** Id */
            id: number;
            /** Study Day Id */
            study_day_id: number;
            state: components["schemas"]["ActivityState"];
            /** Optimistic Version */
            optimistic_version: number;
            classification: components["schemas"]["IncompleteClassification"];
            /** Stronger Evidence Id */
            stronger_evidence_id: number | null;
            /** Activity Focused Seconds */
            activity_focused_seconds: number;
            /** Day Focused Minutes */
            day_focused_minutes: number;
            /** Hard Stop Recommended */
            hard_stop_recommended: boolean;
            open_timer: components["schemas"]["TimerResponse"] | null;
            /**
             * Source Hidden
             * @default false
             */
            source_hidden: boolean;
        };
        /** ActivitySourceReference */
        ActivitySourceReference: {
            /** Path */
            path: string;
            /** Anchor */
            anchor?: string | null;
        };
        /**
         * ActivityState
         * @enum {string}
         */
        ActivityState: "ready" | "active" | "paused" | "output_committed" | "self_review_complete" | "ai_processing" | "feedback_ready" | "correction_due" | "demonstrated" | "needs_work" | "incomplete" | "superseded";
        /** ActivityTaskContract */
        ActivityTaskContract: {
            /** Stable Id */
            stable_id: string;
            /**
             * Block
             * @enum {string}
             */
            block: "sql" | "technical_learning" | "career_pipeline" | "correction_warmup" | "tam_case" | "communication_spoken" | "daily_close" | "saturday_assessment";
            /** Objective */
            objective: string;
            /** Timebox Minutes */
            timebox_minutes: number;
            /** Required */
            required: boolean;
            /** Source References */
            source_references: components["schemas"]["ActivitySourceReference"][];
            /** Required Output */
            required_output: string[];
            /** Pass Criteria */
            pass_criteria: string[];
            /** Evidence Requirements */
            evidence_requirements: string[];
            /**
             * Allowed Ai Role
             * @enum {string}
             */
            allowed_ai_role: "none" | "planner" | "tutor" | "coach" | "interviewer" | "reviewer" | "analyst";
            /** Procedure */
            procedure: components["schemas"]["ActivityProcedureStep"][];
            /** Constraints */
            constraints: string[];
            /** Exercise Type */
            exercise_type: string | null;
            /** Mapping Version */
            mapping_version: string | null;
        };
        /** ArtifactConfirmCommand */
        ArtifactConfirmCommand: {
            /** Expected Version */
            expected_version: number;
            /** Upload Idempotency Key */
            upload_idempotency_key: string;
            /** Object Key */
            object_key: string;
        };
        /** ArtifactPresignCommand */
        ArtifactPresignCommand: {
            /** Expected Version */
            expected_version: number;
            /**
             * Artifact Class
             * @enum {string}
             */
            artifact_class: "original_audio" | "transcript" | "written_output" | "sql_output" | "recall_note" | "case_artifact" | "analysis" | "export";
            /** Sha256 */
            sha256: string;
            /** Byte Length */
            byte_length: number;
            /** Content Type */
            content_type: string;
            /** Original Filename */
            original_filename: string;
        };
        /** ArtifactPresignResponse */
        ArtifactPresignResponse: {
            /** Artifact Id */
            artifact_id?: number | null;
            /** Object Key */
            object_key: string;
            /** Reused */
            reused: boolean;
            upload: components["schemas"]["PresignedUploadResponse"] | null;
        };
        /** ArtifactReference */
        ArtifactReference: {
            /** Artifact Id */
            artifact_id: number;
            /**
             * Link Role
             * @enum {string}
             */
            link_role: "original_output" | "presentation_audio" | "transcript" | "analysis" | "supporting" | "correction";
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Id */
            id: number;
            /** Sha256 */
            sha256: string;
            /** Byte Length */
            byte_length: number;
            /** Content Type */
            content_type: string;
            /** Original Filename */
            original_filename: string;
            /** Artifact Class */
            artifact_class: string;
        };
        /** Body_create_roadmap_import_api_v1_roadmap_imports_post */
        Body_create_roadmap_import_api_v1_roadmap_imports_post: {
            /**
             * Package Kind
             * @enum {string}
             */
            package_kind: "zip" | "folder_entries";
            /** Package */
            package?: string | null;
            /** Paths */
            paths?: string[] | null;
            /** Files */
            files?: string[] | null;
        };
        /** CommitOutputCommand */
        CommitOutputCommand: {
            /** Expected Version */
            expected_version: number;
            /** Client Sequence */
            client_sequence: number;
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /**
             * Artifact Refs
             * @default []
             */
            artifact_refs: components["schemas"]["ArtifactReference"][];
            /** Parent Attempt Id */
            parent_attempt_id?: number | null;
        };
        /** CommittedOutputSummary */
        CommittedOutputSummary: {
            /** Attempt Id */
            attempt_id: number;
            /** Attempt Kind */
            attempt_kind: string;
            /** Commitment Sha256 */
            commitment_sha256: string;
            /** Contract Payload */
            contract_payload: {
                [key: string]: unknown;
            };
            /** Artifact Ids */
            artifact_ids: number[];
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
        };
        /** ContinueAction */
        ContinueAction: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "correction_warmup" | "resume_activity" | "complete_self_review" | "start_activity" | "review_feedback" | "close_day";
            /** Target Id */
            target_id: number;
            /** Label */
            label: string;
            /**
             * Allowed Ai Role
             * @enum {string}
             */
            allowed_ai_role: "none" | "planner" | "tutor" | "coach" | "interviewer" | "reviewer" | "analyst";
        };
        /** DailyCloseCommand */
        DailyCloseCommand: {
            /** Evidence Confirmed */
            evidence_confirmed: boolean;
            evidence_manifest: components["schemas"]["EvidenceManifest"];
            /** Strongest Output */
            strongest_output: string;
            /** Repeated Mistake */
            repeated_mistake: string;
            /**
             * Unfinished Classification
             * @enum {string}
             */
            unfinished_classification: "none" | "required" | "useful" | "optional" | "superseded";
            /** Unfinished Requirement */
            unfinished_requirement: string | null;
            /**
             * Correction Ids
             * @default []
             */
            correction_ids: number[];
        };
        /** DailyCloseResponse */
        DailyCloseResponse: {
            /** Daily Close Id */
            daily_close_id: number;
            /** Study Day Id */
            study_day_id: number;
            /**
             * Day Status
             * @enum {string}
             */
            day_status: "closed" | "incomplete";
            /**
             * Closed At
             * Format: date-time
             */
            closed_at: string;
            /**
             * Consequence
             * @enum {string}
             */
            consequence: "none" | "replace_adaptive" | "retrieval_queue" | "drop" | "link_stronger_evidence";
            /** Replayed */
            replayed: boolean;
        };
        /** EvidenceEventPage */
        EvidenceEventPage: {
            /** Items */
            items: components["schemas"]["EvidenceEventResponse"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** EvidenceEventResponse */
        EvidenceEventResponse: {
            /** Id */
            id: number;
            /** Activity Id */
            activity_id: number;
            /** Attempt Id */
            attempt_id: number | null;
            /** Skill Slug */
            skill_slug: string;
            /** Exercise Type */
            exercise_type: string;
            /** Mapping Version */
            mapping_version: string;
            /** Formula Version */
            formula_version: string;
            /** Rubric Slug */
            rubric_slug: string;
            /** Rubric Version */
            rubric_version: string;
            /** Evaluator */
            evaluator: string;
            /** Practice Mode */
            practice_mode: string;
            /** Assistance */
            assistance: string;
            /** Difficulty */
            difficulty: string;
            /** Performance Score */
            performance_score: string;
            /** Skill Impact */
            skill_impact: string;
            /** Effective Weight */
            effective_weight: string;
            /** Qualifying For Level */
            qualifying_for_level: boolean;
            /** Qualification Reason */
            qualification_reason: string;
            /** Raw Dimension Scores */
            raw_dimension_scores: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** EvidenceManifest */
        EvidenceManifest: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Activity Ids
             * @default []
             */
            activity_ids: number[];
            /**
             * Attempt Ids
             * @default []
             */
            attempt_ids: number[];
            /**
             * Artifact Ids
             * @default []
             */
            artifact_ids: number[];
            /**
             * Self Review Ids
             * @default []
             */
            self_review_ids: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatCommand */
        HeartbeatCommand: {
            /** Expected Version */
            expected_version: number;
            /** Client Sequence */
            client_sequence: number;
        };
        /**
         * IncompleteClassification
         * @enum {string}
         */
        IncompleteClassification: "required" | "useful" | "optional" | "superseded";
        /** IncompleteCommand */
        IncompleteCommand: {
            /** Expected Version */
            expected_version: number;
            classification: components["schemas"]["IncompleteClassification"];
            /** Stronger Evidence Id */
            stronger_evidence_id?: number | null;
        };
        /**
         * NativeOAuthStartRequest
         * @description PKCE-bound native authorization request.
         */
        NativeOAuthStartRequest: {
            /** Code Challenge */
            code_challenge: string;
        };
        /**
         * NativeOAuthStartResponse
         * @description GitHub authorization URL containing only a short-lived opaque state.
         */
        NativeOAuthStartResponse: {
            /** Authorization Url */
            authorization_url: string;
        };
        /**
         * NativeRefreshRequest
         * @description A rotating native refresh credential carried only in a no-store body.
         */
        NativeRefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * NativeSessionResponse
         * @description Minimal owner display for an authenticated native client.
         */
        NativeSessionResponse: {
            /** Github Login */
            github_login: string;
        };
        /**
         * NativeTokenExchangeRequest
         * @description One-time callback code and its RFC 7636 verifier.
         */
        NativeTokenExchangeRequest: {
            /** Code */
            code: string;
            /** Code Verifier */
            code_verifier: string;
        };
        /**
         * NativeTokenResponse
         * @description Short-lived access credential and one replacement refresh credential.
         */
        NativeTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
            /** Github Login */
            github_login: string;
        };
        /** NotificationPage */
        NotificationPage: {
            /** Items */
            items: components["schemas"]["NotificationResponse"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** NotificationResponse */
        NotificationResponse: {
            /** Id */
            id: number;
            /**
             * Notification Type
             * @enum {string}
             */
            notification_type: "feedback_ready" | "correction_due" | "upcoming_real_interview" | "saturday_assessment" | "processing_failure_requires_action";
            /**
             * Subject Kind
             * @enum {string}
             */
            subject_kind: "activity" | "correction" | "interview" | "study_day" | "processing_status";
            /** Subject Id */
            subject_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
        };
        /** OutputCommitResponse */
        OutputCommitResponse: {
            /** Activity Id */
            activity_id: number;
            state: components["schemas"]["ActivityState"];
            /** Optimistic Version */
            optimistic_version: number;
            /** Attempt Id */
            attempt_id: number;
            /** Commitment Sha256 */
            commitment_sha256: string;
            /** Artifact Ids */
            artifact_ids: number[];
        };
        /** PortfolioComponentResponse */
        PortfolioComponentResponse: {
            /** Slug */
            slug: string;
            /** Score */
            score: string;
        };
        /** PortfolioHistoryResponse */
        PortfolioHistoryResponse: {
            /** Items */
            items: components["schemas"]["PortfolioScoreResponse"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** PortfolioScoreResponse */
        PortfolioScoreResponse: {
            /** Id */
            id: number;
            /** Activity Id */
            activity_id: number;
            /** Attempt Id */
            attempt_id: number;
            /** Formula Version */
            formula_version: string;
            /** Rubric Version */
            rubric_version: string;
            /** Total Score */
            total_score: string;
            /** Components */
            components: components["schemas"]["PortfolioComponentResponse"][];
            /** Trend Basis */
            trend_basis: {
                [key: string]: unknown;
            };
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
        };
        /** PresignedUploadResponse */
        PresignedUploadResponse: {
            /** Url */
            url: string;
            /**
             * Method
             * @constant
             */
            method: "PUT";
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /** Expires Seconds */
            expires_seconds: number;
        };
        /**
         * ProblemResponse
         * @description RFC 9457-style public error without provider or secret detail.
         */
        ProblemResponse: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
        };
        /** RoadmapImportResponse */
        RoadmapImportResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Validation Report */
            validation_report: {
                [key: string]: unknown;
            };
            /** Semantic Diff */
            semantic_diff: {
                [key: string]: unknown;
            };
            /** Failure Code */
            failure_code: string | null;
        };
        /** RoadmapVersionResponse */
        RoadmapVersionResponse: {
            /** Id */
            id: number;
            /** Version Key */
            version_key: string;
            /** Version Number */
            version_number: number;
            /** Month Number */
            month_number: number;
            /** State */
            state: string;
            /** Mirror Status */
            mirror_status: string;
            /** Mirror Ref */
            mirror_ref: string | null;
            /** Mirror Error Code */
            mirror_error_code: string | null;
        };
        /** SelfReviewCommand */
        SelfReviewCommand: {
            /** Expected Version */
            expected_version: number;
            /** Main Answer */
            main_answer: string;
            /** Did Well */
            did_well: string;
            /** Structure Weakness */
            structure_weakness: string;
            /** Vague Points */
            vague_points: string;
            /** Hesitation Points */
            hesitation_points: string;
            /** Change Next */
            change_next: string;
            /** Self Score */
            self_score: number;
        };
        /** SelfReviewResponse */
        SelfReviewResponse: {
            /** Activity Id */
            activity_id: number;
            state: components["schemas"]["ActivityState"];
            /** Optimistic Version */
            optimistic_version: number;
            /** Self Review Id */
            self_review_id: number;
            /** Attempt Id */
            attempt_id: number;
            /** Self Score */
            self_score: number;
        };
        /** SelfReviewSummary */
        SelfReviewSummary: {
            /** Id */
            id: number;
            /** Attempt Id */
            attempt_id: number;
            /** Self Score */
            self_score: number;
            /** Main Answer */
            main_answer: string;
            /** Did Well */
            did_well: string;
            /** Structure Weakness */
            structure_weakness: string;
            /** Vague Points */
            vague_points: string;
            /** Hesitation Points */
            hesitation_points: string;
            /** Change Next */
            change_next: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /**
         * SessionResponse
         * @description The authenticated browser's minimal owner display and CSRF view.
         */
        SessionResponse: {
            /** Github Login */
            github_login: string;
            /** Csrf Token */
            csrf_token: string;
        };
        /** SkillListResponse */
        SkillListResponse: {
            /** Items */
            items: components["schemas"]["SkillSummaryResponse"][];
        };
        /** SkillSnapshotResponse */
        SkillSnapshotResponse: {
            /** Id */
            id: number;
            /** Formula Version */
            formula_version: string;
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Estimated Level */
            estimated_level: string;
            /** Confidence */
            confidence: string;
            /** Trend */
            trend: string;
            /** Recency */
            recency: string;
            /** Baseline Target Gap */
            baseline_target_gap: string;
            /** Month One Target Gap */
            month_one_target_gap: string;
            /** Final Target Gap */
            final_target_gap: string;
            /** Total Effective Weight */
            total_effective_weight: string;
            /** Qualifying Event Count */
            qualifying_event_count: number;
            /** Exercise Type Count */
            exercise_type_count: number;
            /** Last Strong Evidence Date */
            last_strong_evidence_date: string | null;
            /** Manifest */
            manifest: components["schemas"]["SnapshotManifestItem"][];
            /** Confidence Basis */
            confidence_basis: {
                [key: string]: unknown;
            };
            /** Trend Basis */
            trend_basis: {
                [key: string]: unknown;
            };
        };
        /** SkillSummaryResponse */
        SkillSummaryResponse: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Baseline */
            baseline: string;
            /** Month One Target */
            month_one_target: string;
            /** Final Target */
            final_target: string;
            latest_snapshot: components["schemas"]["SkillSnapshotResponse"] | null;
        };
        /** SnapshotManifestItem */
        SnapshotManifestItem: {
            /** Event Id */
            event_id: number;
            /** Effective Weight */
            effective_weight: string;
            /**
             * Inclusion Code
             * @enum {string}
             */
            inclusion_code: "included" | "discounted_same_day" | "excluded_nonqualifying" | "excluded_outside_window";
        };
        /** SourceVisibilityCommand */
        SourceVisibilityCommand: {
            /** Expected Version */
            expected_version: number;
            /** Hidden */
            hidden: boolean;
        };
        /** TimerResponse */
        TimerResponse: {
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Last Heartbeat At
             * Format: date-time
             */
            last_heartbeat_at: string;
            /** Counted Seconds */
            counted_seconds: number;
            /** Last Client Sequence */
            last_client_sequence: number;
        };
        /** TodayAnalysis */
        TodayAnalysis: {
            /** Activity Id */
            activity_id: number;
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "needs_attention";
            /**
             * Progress Label
             * @enum {string}
             */
            progress_label: "ready" | "action_required";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TodayBlock */
        TodayBlock: {
            /** Name */
            name: string;
            /** Planned Minutes */
            planned_minutes: number;
            /** Activity Ids */
            activity_ids: number[];
        };
        /** TodayCorrection */
        TodayCorrection: {
            /** Id */
            id: number;
            /**
             * Priority
             * @enum {integer}
             */
            priority: 1 | 2;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Instruction */
            instruction: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "scheduled";
            /** Attempt B Activity Id */
            attempt_b_activity_id: number | null;
        };
        /** TodayInterview */
        TodayInterview: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Stage */
            stage: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Expected Duration Minutes */
            expected_duration_minutes: number;
            /**
             * Privacy Permission Code
             * @enum {string}
             */
            privacy_permission_code: "permission_not_requested" | "permission_granted" | "permission_denied" | "recording_prohibited";
        };
        /** TodayResponse */
        TodayResponse: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Timezone */
            timezone: string;
            /** Day Id */
            day_id: number | null;
            /**
             * Day Type
             * @enum {string}
             */
            day_type: "weekday" | "saturday" | "sunday" | "interview";
            /**
             * Day Status
             * @enum {string}
             */
            day_status: "off" | "planned" | "in_progress" | "closed" | "incomplete" | "skipped";
            roadmap: components["schemas"]["TodayRoadmap"];
            /** Total Planned Minutes */
            total_planned_minutes: number;
            time_policy: components["schemas"]["TodayTimePolicy"];
            /** Required Blocks */
            required_blocks: components["schemas"]["TodayBlock"][];
            /** Tasks */
            tasks: components["schemas"]["TodayTaskCard"][];
            /** Corrections */
            corrections: components["schemas"]["TodayCorrection"][];
            /** Interviews */
            interviews: components["schemas"]["TodayInterview"][];
            /** Awaiting Self Reviews */
            awaiting_self_reviews: components["schemas"]["TodaySelfReview"][];
            /** Analyses */
            analyses: components["schemas"]["TodayAnalysis"][];
            primary_continue: components["schemas"]["ContinueAction"] | null;
            /**
             * Source Updated At
             * Format: date-time
             */
            source_updated_at: string;
            /** Read Model Version */
            read_model_version: string;
            /** Etag */
            etag: string;
        };
        /** TodayRoadmap */
        TodayRoadmap: {
            /** Version Id */
            version_id: number;
            /** Version Key */
            version_key: string;
            /** Version Number */
            version_number: number;
            /** Month */
            month: number;
            /** Week */
            week: number;
            /** Day */
            day: number;
        };
        /** TodaySelfReview */
        TodaySelfReview: {
            /** Activity Id */
            activity_id: number;
            /** Objective */
            objective: string;
            /**
             * Output Committed At
             * Format: date-time
             */
            output_committed_at: string;
        };
        /** TodaySourceReference */
        TodaySourceReference: {
            /** Path */
            path: string;
            /** Anchor */
            anchor?: string | null;
        };
        /** TodayTaskCard */
        TodayTaskCard: {
            /** Activity Id */
            activity_id: number;
            /** Roadmap Order */
            roadmap_order: number;
            /** Stable Id */
            stable_id: string;
            /**
             * Block
             * @enum {string}
             */
            block: "sql" | "technical_learning" | "career_pipeline" | "correction_warmup" | "tam_case" | "communication_spoken" | "daily_close" | "saturday_assessment";
            state: components["schemas"]["ActivityState"];
            /** Objective */
            objective: string;
            /** Timebox Minutes */
            timebox_minutes: number;
            /** Source References */
            source_references: components["schemas"]["TodaySourceReference"][];
            /** Required Output */
            required_output: string[];
            /** Pass Criteria */
            pass_criteria: string[];
            /**
             * Allowed Ai Role
             * @enum {string}
             */
            allowed_ai_role: "none" | "planner" | "tutor" | "coach" | "interviewer" | "reviewer" | "analyst";
            /** Evidence Requirements */
            evidence_requirements: string[];
            /** Required */
            required: boolean;
            /** Optimistic Version */
            optimistic_version: number;
        };
        /** TodayTimePolicy */
        TodayTimePolicy: {
            /** Target Minutes */
            target_minutes: number;
            /** Acceptable Minimum */
            acceptable_minimum: number;
            /** Hard Stop Minutes */
            hard_stop_minutes: number;
            /** Focused Minutes */
            focused_minutes: number;
            /** Hard Stop Recommended */
            hard_stop_recommended: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionedCommand */
        VersionedCommand: {
            /** Expected Version */
            expected_version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_api_v1_auth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                tamforge_oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    native_start_api_v1_auth_native_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeOAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeOAuthStartResponse"];
                };
            };
            /** @description Invalid native authentication request. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Native authentication is temporarily busy. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    native_exchange_api_v1_auth_native_exchange_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeTokenExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeTokenResponse"];
                };
            };
            /** @description Invalid native authentication request. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    native_refresh_api_v1_auth_native_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeTokenResponse"];
                };
            };
            /** @description Invalid native authentication request. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    native_revoke_api_v1_auth_native_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid native authentication request. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    native_session_api_v1_auth_native_session_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_csrf?: string | null;
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_v1_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_activity_artifact_api_v1_activities__activity_id__artifacts_presign_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactPresignCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactPresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_activity_artifact_api_v1_activities__activity_id__artifacts_confirm_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactConfirmCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_activity_source_visibility_api_v1_activities__activity_id__source_visibility_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceVisibilityCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_activity_output_api_v1_activities__activity_id__commit_output_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitOutputCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputCommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_activity_self_review_api_v1_activities__activity_id__self_review_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelfReviewCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_activity_api_v1_activities__activity_id__start_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionedCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_activity_api_v1_activities__activity_id__pause_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_activity_api_v1_activities__activity_id__resume_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionedCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_activity_api_v1_activities__activity_id__heartbeat_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_activity_incomplete_api_v1_activities__activity_id__classify_incomplete_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncompleteCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_api_v1_skills__skill_slug__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                skill_slug: string;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skill_evidence_api_v1_skills__skill_slug__evidence_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                skill_slug: string;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_evidence_api_v1_activities__activity_id__evidence_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                activity_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_history_api_v1_portfolio_judgment_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_notification_read_api_v1_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                notification_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_status_events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_roadmap_import_api_v1_roadmap_imports_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_roadmap_import_api_v1_roadmap_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roadmap_import_api_v1_roadmap_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                import_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_roadmap_import_api_v1_roadmap_imports__import_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                import_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_roadmap_mirror_api_v1_roadmap_imports__version_id__mirror_retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roadmap_versions_api_v1_roadmap_versions_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_roadmap_version_api_v1_roadmap_versions__version_id__activate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                version_id: number;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_api_v1_today_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_today_api_v1_today__local_date__close_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                local_date: string;
            };
            cookie?: {
                tamforge_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyCloseCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCloseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
